title: Settings
data:
  favicon: brand/favicon.png
  site_name: "Br√≠d O' Meara Consultancy"
  logo: brand/BridOMeara_Landscape_Final_Logo.svg
  watermark: brand/BridOMeara_Symbol_Watermark.svg
  social:
    -
      id: eZspu4mg
      name: LinkedIn
      url: 'https://www.linkedin.com/in/br%C3%ADd-o-meara-90a39736/'
      icon: social_icons/linkedin.svg
    -
      id: PmGjGdLA
      name: Email
      url: 'mailto:brid@bridomeara.ie'
      icon: social_icons/email.svg
